services:
  wordpress:
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    container_name: wordpress-nginx
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_REDIS_HOST: redis
    volumes:
      - wp-content:/var/www/html/wp-content
      - ./wordpress/wp-config.php:/var/www/html/wp-config.php
    depends_on:
      - mysql
      - redis
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - wp-content:/var/www/http/wp-content
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wordpress
    ports:
      - "8080:80"

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  wp-content:
  db_data:
  redis_data: